name: My First Workflow

on: [push]  # This workflow will run on every push to the repository

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Action to check out your repository's code

    - name: Run a simple command
      run: echo "Hello, GitHub Actions!"